In [1]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
from pathlib import Path
import json
import sys
import pandas as pd

PROJECT_DIR = Path("/content/drive/MyDrive/Chunkbench")
CHUNKERS_DIR = PROJECT_DIR / "chunkers"
INPUT_DIR = PROJECT_DIR / "input"
OUTPUT_DIR = PROJECT_DIR / "output"
PREPROCESSING_DIR = PROJECT_DIR / "preprocessing"

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

print("Proyecto encontrado:", PROJECT_DIR.exists())
print("Ruta activa:", PROJECT_DIR)

Proyecto encontrado: True
Ruta activa: /content/drive/MyDrive/Chunkbench

In [10]:
from preprocessing.json_to_text import json_to_text

from chunkers.rulebased.fixed_character_chunking import FixedCharacterChunker
from chunkers.rulebased.fixed_token_chunking import FixedTokenChunker
from chunkers.rulebased.overlapping_token_chunking import OverlappingTokenChunker
from chunkers.rulebased.sliding_window_token_chunking import SlidingWindowTokenChunker
from chunkers.rulebased.length_aware_chunking import LengthAwareChunker
from chunkers.rulebased.sentence_based_chunking import SentenceBasedChunker
from chunkers.rulebased.sentence_group_chunking import SentenceGroupChunker
from chunkers.rulebased.paragraph_based_chunking import ParagraphBasedChunker
from chunkers.rulebased.paragraph_group_chunking import ParagraphGroupChunker

from chunkers.recursive.recursive_chunking import RecursiveChunker
from chunkers.recursive.recursive_token_chunking import RecursiveTokenChunker
from chunkers.recursive.parent_child_chunking import ParentChildChunker

from chunkers.semantic.semantic_embedding_based_chunking import SemanticEmbeddingChunker
from chunkers.semantic.semantic_similarity_threshold_chunking import SemanticSimilarityThresholdChunker
from chunkers.semantic.topic_based_chunking import TopicBasedChunker
from chunkers.semantic.semantic_boundary_detection import SemanticBoundaryChunker

from chunkers.dynamic.content_density_adaptive_chunking import ContentDensityAdaptiveChunker
from chunkers.dynamic.dynamic_token_size_chunking import DynamicTokenSizeChunker
from chunkers.dynamic.semantic_variance_adaptive_chunking import SemanticVarianceAdaptiveChunker

from chunkers.llm.llm_boundary_detection_chunking import LLMBoundaryDetectionChunker
from chunkers.llm.llm_segment_then_chunk import LLMSegmentThenChunker

In [11]:
json_path = INPUT_DIR / "EAU-Guidelines-on-Paediatric-Urology-2025.json"

with json_path.open("r", encoding="utf-8") as file:
    document = json.load(file)

document_text = json_to_text(document)

print("JSON cargado correctamente.")

JSON cargado correctamente.

## Métodos deterministas

### Fixed Character Chunking
División del texto cada número fijo de caracteres (se puede añadir overlap)

In [ ]:
fixed_character_chunking = FixedCharacterChunker(
    chunk_size=2000,
    overlap=200,
)

fixed_character_chunks = fixed_character_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(fixed_character_chunks)}")

for chunk in fixed_character_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 31
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 0, 'end_char': 2000, 'character_count': 2000}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, di

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 1800, 'end_char': 3800, 'character_count': 2000}
------------------------------------------------------------------------------------------
t conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circ

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 3600, 'end_char': 5600, 'character_count': 2000}
------------------------------------------------------------------------------------------
ended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 5400, 'end_char': 7400, 'character_count': 2000}
------------------------------------------------------------------------------------------
_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral rec

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 7200, 'end_char': 9200, 'character_count': 2000}
------------------------------------------------------------------------------------------
ary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommend

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 9000, 'end_char': 11000, 'character_count': 2000}
------------------------------------------------------------------------------------------
ngal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal steno

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 10800, 'end_char': 12800, 'character_count': 2000}
------------------------------------------------------------------------------------------
ral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicit

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 12600, 'end_char': 14600, 'character_count': 2000}
------------------------------------------------------------------------------------------
on by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug. Mechanism: Beta-3 agonist that relaxes the bladder muscle, used for overactive bladder treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as monotherapy or add-on therapy. Name: Transcutaneous electrical nerve stimulation (TENS). Type: procedure. Mechanism:

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_character_chunking', 'chunk_size': 2000, 'overlap': 200, 'start_char': 14400, 'end_char': 16400, 'character_count': 2000}

### Fixed Token Chunking
Tokenización y división cada número fijo de tokens

In [ ]:
fixed_token_chunking = FixedTokenChunker(
    chunk_size=500,
    overlap=75,
)

fixed_token_chunks = fixed_token_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(fixed_token_chunks)}")

for chunk in fixed_token_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 30
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 0, 'end_token': 500, 'token_count': 500}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease,

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 425, 'end_token': 925, 'token_count': 500}
------------------------------------------------------------------------------------------
, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 850, 'end_token': 1350, 'token_count': 500}
------------------------------------------------------------------------------------------
 urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.



==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 1275, 'end_token': 1775, 'token_count': 500}
------------------------------------------------------------------------------------------
: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hy

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 1700, 'end_token': 2200, 'token_count': 500}
------------------------------------------------------------------------------------------
ral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 2125, 'end_token': 2625, 'token_count': 500}
------------------------------------------------------------------------------------------
 Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'fixed_token_chunking', 'chunk_size': 500, 'overlap': 75, 'start_token': 2550, 'end_token': 3050, 'token_count': 500}
------------------------------------------------------------------------------------------
 Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug. Mechanism: Beta-3 agonist that relaxes the bladder muscle, used for overactive bladder treatment.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025

### Overlapping Token Chunking
Tokenización y división cada número fijo de tokens con overlap

In [ ]:
overlapping_token_chunking = OverlappingTokenChunker(
    chunk_size=500,
    overlap_size=75,
)

overlapping_token_chunks = overlapping_token_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(overlapping_token_chunks)}")

for chunk in overlapping_token_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 30
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 0, 'end_token': 500, 'token_count': 500}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease,

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 425, 'end_token': 925, 'token_count': 500}
------------------------------------------------------------------------------------------
, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 850, 'end_token': 1350, 'token_count': 500}
------------------------------------------------------------------------------------------
 urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.



==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 1275, 'end_token': 1775, 'token_count': 500}
------------------------------------------------------------------------------------------
: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hy

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 1700, 'end_token': 2200, 'token_count': 500}
------------------------------------------------------------------------------------------
ral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 2125, 'end_token': 2625, 'token_count': 500}
------------------------------------------------------------------------------------------
 Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 2550, 'end_token': 3050, 'token_count': 500}
------------------------------------------------------------------------------------------
 Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug. Mechanism: Beta-3 agonist that relaxes the bladder muscle, used for overactive bladder treatment.

==========================================================================================

### Sliding Window Token Chunking
Tokenización y desplazamiento de una ventana de tamaño fijo

In [ ]:
sliding_window_token_chunking = OverlappingTokenChunker(
    chunk_size=500,
    overlap_size=75,
)

sliding_window_token_chunks = sliding_window_token_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(sliding_window_token_chunks)}")

for chunk in sliding_window_token_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 30
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 0, 'end_token': 500, 'token_count': 500}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease,

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 425, 'end_token': 925, 'token_count': 500}
------------------------------------------------------------------------------------------
, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 850, 'end_token': 1350, 'token_count': 500}
------------------------------------------------------------------------------------------
 urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.



==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 1275, 'end_token': 1775, 'token_count': 500}
------------------------------------------------------------------------------------------
: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hy

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 1700, 'end_token': 2200, 'token_count': 500}
------------------------------------------------------------------------------------------
ral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 2125, 'end_token': 2625, 'token_count': 500}
------------------------------------------------------------------------------------------
 Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'overlapping_token_chunking', 'chunk_size': 500, 'overlap_size': 75, 'start_token': 2550, 'end_token': 3050, 'token_count': 500}
------------------------------------------------------------------------------------------
 Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug. Mechanism: Beta-3 agonist that relaxes the bladder muscle, used for overactive bladder treatment.

==========================================================================================

### Length Aware Chunking
Separa el texto en frases y y las agrupa intentando acercarse a una longitud objetivo sin pasarla

In [ ]:
length_aware_chunking = LengthAwareChunker(
    target_length=2000,
    tolerance=75,
)

length_aware_chunks = length_aware_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(length_aware_chunks)}")

for chunk in length_aware_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 28
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 1569, 'sentence_count': 44}
------------------------------------------------------------------------------------------
Schema version: 1.0. Document type: clinical_guideline. Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2061, 'sentence_count': 21}
------------------------------------------------------------------------------------------
Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2007, 'sentence_count': 28}
------------------------------------------------------------------------------------------
Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2024, 'sentence_count': 35}
------------------------------------------------------------------------------------------
Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice. Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2050, 'sentence_count': 39}
------------------------------------------------------------------------------------------
Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2060, 'sentence_count': 36}
------------------------------------------------------------------------------------------
Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML. Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2013, 'sentence_count': 33}
------------------------------------------------------------------------------------------
Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 2048, 'sentence_count': 36}
------------------------------------------------------------------------------------------
Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug. Mechanism: Beta-3 agonist that relaxes the bladder muscle, used for overactive bladder treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as monotherapy or add-on therapy. Name: Transcutaneous electrical nerve stimulation (TENS). Type: procedure. Mechanism: Neuromodulation technique using electrical stimulation for urinary and faecal incontinence. Approved indications: Daytime lower urinary tract conditions. Administration: Non-invasive electrical stimulation therapy. Name: Percutaneous tibial nerve stimulation (PTNS). Type: procedure. Mechanism: Neuromodulation technique involving stimulation of the tibial nerve for incontinence treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Minimally invasive electrical stimulation therapy. Name: Sacral neuromodulation (SNM). Type: procedure. Mechanism: Neuromodulation technique involving implantation of a device to stimulate sacral nerves for bladder control. Approved indications: Daytime lower urinary tract conditions. Administration: Surgical implantation procedure. Name: Botulinum toxin A (BoNT-A). Type: drug. Mechanism: Neurotoxin used to relax muscles, injected for bladder overactivity treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Cystoscopic injection into the bladder wall. Name: Trimethoprim. Type: drug. Mechanism: Antibacterial agent that inhibits bacterial folate synthesis. Approved indications: Antibacterial prophylaxis for urinary tract infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'length_aware_chunking', 'target_length': 2000, 'tolerance': 75, 'min_length': 1925, 'max_length': 2075, 'length': 1987, 'sentence_count': 40}

### Sentence Based Chunking
Detecta las frases y convierte cada una en un chunk independiente

In [ ]:
sentence_based_chunking = SentenceBasedChunker()

sentence_based_chunks = sentence_based_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(sentence_based_chunks)}")

for chunk in sentence_based_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Se han truncado las últimas 5000 líneas del flujo de salida.
Type: regimen.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0276
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 276, 'character_count': 43}
------------------------------------------------------------------------------------------
Components: Trimethoprim, Sulfamethoxazole.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0277
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 277, 'character_count': 59}
------------------------------------------------------------------------------------------
Mechanism: Combination antibacterial agent for prophylaxis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0278
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 278, 'character_count': 77}
------------------------------------------------------------------------------------------
Approved indications: Antibacterial prophylaxis for urinary tract infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0279
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 279, 'character_count': 74}
------------------------------------------------------------------------------------------
Administration: Oral prophylactic dosage of 1-2 mg/kg body weight per day.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0280
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 280, 'character_count': 52}
------------------------------------------------------------------------------------------
Monitoring: Not recommended under two months of age.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0281
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 281, 'character_count': 23}
------------------------------------------------------------------------------------------
Name: Sulfamethoxazole.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0282
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 282, 'character_count': 11}
------------------------------------------------------------------------------------------
Type: drug.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0283
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 283, 'character_count': 69}
------------------------------------------------------------------------------------------
Mechanism: Antibacterial agent used in combination with trimethoprim.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0284
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 284, 'character_count': 77}
------------------------------------------------------------------------------------------
Approved indications: Antibacterial prophylaxis for urinary tract infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0285
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 285, 'character_count': 74}
------------------------------------------------------------------------------------------
Administration: Oral prophylactic dosage of 1-2 mg/kg body weight per day.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0286
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 286, 'character_count': 38}
------------------------------------------------------------------------------------------
Monitoring: Until three months of age.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0287
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 287, 'character_count': 21}
------------------------------------------------------------------------------------------
Name: Nitrofurantoin.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0288
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 288, 'character_count': 11}
------------------------------------------------------------------------------------------
Type: drug.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0289
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 289, 'character_count': 70}
------------------------------------------------------------------------------------------
Mechanism: Antibacterial agent that inhibits bacterial enzyme systems.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0290
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 290, 'character_count': 77}
------------------------------------------------------------------------------------------
Approved indications: Antibacterial prophylaxis for urinary tract infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0291
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 291, 'character_count': 74}
------------------------------------------------------------------------------------------
Administration: Oral prophylactic dosage of 1-2 mg/kg body weight per day.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0292
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 292, 'character_count': 52}
------------------------------------------------------------------------------------------
Monitoring: Not recommended under two months of age.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0293
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 293, 'character_count': 15}
------------------------------------------------------------------------------------------
Name: Cefaclor.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0294
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 294, 'character_count': 11}
------------------------------------------------------------------------------------------
Type: drug.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0295
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 295, 'character_count': 80}
------------------------------------------------------------------------------------------
Mechanism: Cephalosporin antibiotic that inhibits bacterial cell wall synthesis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0296
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 296, 'character_count': 77}
------------------------------------------------------------------------------------------
Approved indications: Antibacterial prophylaxis for urinary tract infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0297
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 297, 'character_count': 73}
------------------------------------------------------------------------------------------
Administration: Oral prophylactic dosage of 10 mg/kg body weight per day.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0298
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 298, 'character_count': 31}
------------------------------------------------------------------------------------------
Monitoring: No age limitations.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0299
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 299, 'character_count': 14}
------------------------------------------------------------------------------------------
Name: Cefixim.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0300
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 300, 'character_count': 11}
------------------------------------------------------------------------------------------
Type: drug.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0301
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 301, 'character_count': 62}
------------------------------------------------------------------------------------------
Mechanism: Cephalosporin antibiotic for bacterial prophylaxis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0302
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 302, 'character_count': 77}
------------------------------------------------------------------------------------------
Approved indications: Antibacterial prophylaxis for urinary tract infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0303
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 303, 'character_count': 72}
------------------------------------------------------------------------------------------
Administration: Oral prophylactic dosage of 2 mg/kg body weight per day.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0304
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 304, 'character_count': 34}
------------------------------------------------------------------------------------------
Monitoring: Preterms and newborns.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0305
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 305, 'character_count': 25}
------------------------------------------------------------------------------------------
Name: Cranberry products.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0306
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 306, 'character_count': 12}
------------------------------------------------------------------------------------------
Type: other.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0307
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 307, 'character_count': 106}
------------------------------------------------------------------------------------------
Mechanism: Non-antibiotic prophylactic measure thought to prevent bacterial adhesion in the urinary tract.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0308
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 308, 'character_count': 109}
------------------------------------------------------------------------------------------
Approved indications: Prevention of urinary tract infection recurrence in children with normal urinary tract.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0309
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 309, 'character_count': 37}
------------------------------------------------------------------------------------------
Administration: Oral supplementation.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0310
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 310, 'character_count': 17}
------------------------------------------------------------------------------------------
Name: Probiotics.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0311
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 311, 'character_count': 12}
------------------------------------------------------------------------------------------
Type: other.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0312
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 312, 'character_count': 95}
------------------------------------------------------------------------------------------
Mechanism: Non-antibiotic prophylactic measure using beneficial bacteria to prevent infections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0313
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 313, 'character_count': 109}
------------------------------------------------------------------------------------------
Approved indications: Prevention of urinary tract infection recurrence in children with normal urinary tract.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0314
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 314, 'character_count': 37}
------------------------------------------------------------------------------------------
Administration: Oral supplementation.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0315
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 315, 'character_count': 28}
------------------------------------------------------------------------------------------
Name: Vitamin A. Type: drug.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0316
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 316, 'character_count': 71}
------------------------------------------------------------------------------------------
Mechanism: Supplement with potential role in preventing renal scarring.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0317
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 317, 'character_count': 89}
------------------------------------------------------------------------------------------
Approved indications: Prevention of renal scarring in children with acute pyelonephritis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0318
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 318, 'character_count': 37}
------------------------------------------------------------------------------------------
Administration: Oral supplementation.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0319
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_based_chunking', 'sentence_index': 319, 'character_count': 28}
------------------------------------------------------------------------------------------
Name: Vitamin E. Type: drug.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0320
Documento: EAU-Guidelines-on-Paediatric-Urology-2025

### Sentence Group Chunking
Agrupa un número fijo de frases consecutivas en cada chunk, permite overlap de frases

In [ ]:
sentence_group_chunking = SentenceGroupChunker(
    sentences_per_chunk=20,
    overlap=2,
)

sentence_group_chunks = sentence_group_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(sentence_group_chunks)}")

for chunk in sentence_group_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 55
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 0, 'end_sentence_index': 20, 'sentence_count': 20, 'character_count': 385}
------------------------------------------------------------------------------------------
Schema version: 1.0. Document type: clinical_guideline. Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 18, 'end_sentence_index': 38, 'sentence_count': 20, 'character_count': 346}
------------------------------------------------------------------------------------------
Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 36, 'end_sentence_index': 56, 'sentence_count': 20, 'character_count': 2259}
------------------------------------------------------------------------------------------
Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 54, 'end_sentence_index': 74, 'sentence_count': 20, 'character_count': 1459}
------------------------------------------------------------------------------------------
Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 72, 'end_sentence_index': 92, 'sentence_count': 20, 'character_count': 1358}
------------------------------------------------------------------------------------------
Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 90, 'end_sentence_index': 110, 'sentence_count': 20, 'character_count': 1259}
------------------------------------------------------------------------------------------
Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice. Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 108, 'end_sentence_index': 128, 'sentence_count': 20, 'character_count': 1033}
------------------------------------------------------------------------------------------
Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 126, 'end_sentence_index': 146, 'sentence_count': 20, 'character_count': 972}
------------------------------------------------------------------------------------------
Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 144, 'end_sentence_index': 164, 'sentence_count': 20, 'character_count': 933}
------------------------------------------------------------------------------------------
Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 162, 'end_sentence_index': 182, 'sentence_count': 20, 'character_count': 1292}
------------------------------------------------------------------------------------------
Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML. Therapies index.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 180, 'end_sentence_index': 200, 'sentence_count': 20, 'character_count': 1057}
------------------------------------------------------------------------------------------
Pathogen or syndrome: PML. Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 198, 'end_sentence_index': 218, 'sentence_count': 20, 'character_count': 1139}
------------------------------------------------------------------------------------------
Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'sentence_group_chunking', 'sentences_per_chunk': 20, 'overlap': 2, 'start_sentence_index': 216, 'end_sentence_index': 236, 'sentence_count': 20, 'character_count': 1272}
------------------------------------------------------------------------------------------

### Paragraph Based Chunking
Considera cada párrafo como un chunk independiente

In [ ]:
paragraph_based_chunking = ParagraphBasedChunker()

paragraph_based_chunks = paragraph_based_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(paragraph_based_chunks)}")

for chunk in paragraph_based_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 14
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 0, 'character_count': 20}
------------------------------------------------------------------------------------------
Schema version: 1.0.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 1, 'character_count': 34}
------------------------------------------------------------------------------------------
Document type: clinical_guideline.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 2, 'character_count': 1506}
------------------------------------------------------------------------------------------
Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 3, 'character_count': 1009}
------------------------------------------------------------------------------------------
Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 4, 'character_count': 3997}
------------------------------------------------------------------------------------------
Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 5, 'character_count': 4045}
------------------------------------------------------------------------------------------
Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_based_chunking', 'paragraph_index': 6, 'character_count': 8396}
------------------------------------------------------------------------------------------

### Paragraph Group Chunking
Agrupa un número fijo de párrafos consecutivos en cada chunk, permite overlap de párrafos

In [ ]:
paragraph_group_chunking = ParagraphGroupChunker(
    paragraphs_per_chunk=3,
    overlap=1,
)

paragraph_group_chunks = paragraph_group_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(paragraph_group_chunks)}")

for chunk in paragraph_group_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 7
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_group_chunking', 'paragraphs_per_chunk': 3, 'overlap': 1, 'start_paragraph_index': 0, 'end_paragraph_index': 3, 'paragraph_count': 3, 'character_count': 1564}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_group_chunking', 'paragraphs_per_chunk': 3, 'overlap': 1, 'start_paragraph_index': 2, 'end_paragraph_index': 5, 'paragraph_count': 3, 'character_count': 6516}
------------------------------------------------------------------------------------------
Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'paragraph_group_chunking', 'paragraphs_per_chunk': 3, 'overlap': 1, 'start_paragraph_index': 4, 'end_paragraph_index': 7, 'paragraph_count': 3, 'character_count': 16442}
------------------------------------------------------------------------------------------
Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.


### Resumen

In [ ]:
chunk_results_rulebased = {
    "Fixed Character": fixed_character_chunks,
    "Fixed Token": fixed_token_chunks,
    "Length Aware": length_aware_chunks,
    "Overlapping Token": overlapping_token_chunks,
    "Paragraph Based": paragraph_based_chunks,
    "Paragraph Group": paragraph_group_chunks,
    "Sentence Based": sentence_based_chunks,
    "Sentence Group": sentence_group_chunks,
    "Sliding Window Token": sliding_window_token_chunks,
}


results_rulebased = []

for method_name, method_chunks in chunk_results_rulebased.items():
    lengths = [len(chunk.text) for chunk in method_chunks]

    results_rulebased.append(
        {
            "Método": method_name,
            "Número de chunks": len(method_chunks),
            "Longitud mínima": min(lengths) if lengths else 0,
            "Longitud máxima": max(lengths) if lengths else 0,
            "Longitud media": (
                round(sum(lengths) / len(lengths), 2)
                if lengths
                else 0
            ),
        }
    )


results_rulebased_df = pd.DataFrame(results_rulebased)

results_rulebased_df

,Método,Número de chunks,Longitud mínima,Longitud máxima,Longitud media
0,Fixed Character,31,800,2000,1961.29
1,Fixed Token,30,822,2725,2151.77
2,Length Aware,28,522,2069,1955.71
3,Overlapping Token,30,822,2725,2151.77
4,Paragraph Based,14,20,19809,3912.43
5,Paragraph Group,7,1564,33410,13506.71
6,Sentence Based,990,5,661,54.34
7,Sentence Group,55,338,2326,1106.45
8,Sliding Window Token,30,822,2725,2151.77

## Métodos recursivos

### Recursive Chunking
Divide por separadores naturales hasta cumplir un tamaño máximo de caracteres

In [ ]:
recursive_chunking = RecursiveChunker(
    chunk_size=2000,
    chunk_overlap=200,
)

recursive_chunks = recursive_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(recursive_chunks)}")

for chunk in recursive_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 35
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1564}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1009}
------------------------------------------------------------------------------------------
Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1856}
------------------------------------------------------------------------------------------
Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1992}
------------------------------------------------------------------------------------------
. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 517}
------------------------------------------------------------------------------------------
. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1982}
------------------------------------------------------------------------------------------
Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1817}
------------------------------------------------------------------------------------------
. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI)

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 524}
------------------------------------------------------------------------------------------
. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1916}
------------------------------------------------------------------------------------------
Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1934}
------------------------------------------------------------------------------------------
. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_chunking', 'chunk_size': 2000, 'chunk_overlap': 200, 'character_count': 1997}
------------------------------------------------------------------------------------------

### Recursive Token Fallback Chunking
Divide por separadores naturales hasta cumplir un tamaño máximo de tokens

In [ ]:
recursive_token_chunking = RecursiveTokenChunker(
    chunk_size=400,
    chunk_overlap=60,
    encoding_name="cl100k_base",
)

recursive_token_chunks = recursive_token_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(recursive_token_chunks)}")

for chunk in recursive_token_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 41
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 15, 'character_count': 56}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 398, 'character_count': 1542}
------------------------------------------------------------------------------------------
Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 213, 'character_count': 1009}
------------------------------------------------------------------------------------------
Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 391, 'character_count': 2167}
------------------------------------------------------------------------------------------
Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 398, 'character_count': 2141}
------------------------------------------------------------------------------------------
. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 372, 'character_count': 1649}
------------------------------------------------------------------------------------------
Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 380, 'character_count': 1751}
------------------------------------------------------------------------------------------
. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 226, 'character_count': 1065}
------------------------------------------------------------------------------------------
. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 386, 'character_count': 1725}
------------------------------------------------------------------------------------------
Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'recursive_token_fallback_chunking', 'chunk_size': 400, 'chunk_overlap': 60, 'encoding_name': 'cl100k_base', 'token_count': 396, 'character_count': 1902}
------------------------------------------------------------------------------------------
. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis. Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010

### Parent Child Chunking
Crea chunks padres grandes y subdivide cada uno en chunks hijos más pequeños relacionados a los padres

In [ ]:
parent_child_chunking = ParentChildChunker(
    parent_chunk_size=2000,
    child_chunk_size=1200,
    chunk_overlap=100,
)

parent_child_chunks = parent_child_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(f"Número total de chunks: {len(parent_child_chunks)}")

for chunk in parent_child_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 98
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'parent', 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1564}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000_child_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000', 'parent_index': 0, 'child_index': 0, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 56}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000_child_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000', 'parent_index': 0, 'child_index': 1, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 902}
------------------------------------------------------------------------------------------
Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000_child_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0000', 'parent_index': 0, 'child_index': 2, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 604}
------------------------------------------------------------------------------------------
. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'parent', 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1009}
------------------------------------------------------------------------------------------
Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0001_child_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0001', 'parent_index': 1, 'child_index': 0, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1009}
------------------------------------------------------------------------------------------
Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'parent', 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1856}
------------------------------------------------------------------------------------------
Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0002_child_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0002', 'parent_index': 2, 'child_index': 0, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1193}
------------------------------------------------------------------------------------------
Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0002_child_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0002', 'parent_index': 2, 'child_index': 1, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 663}
------------------------------------------------------------------------------------------
. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'parent', 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1859}
------------------------------------------------------------------------------------------
. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0003_child_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0003', 'parent_index': 3, 'child_index': 0, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 1187}
------------------------------------------------------------------------------------------
. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0003_child_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'child', 'parent_id': 'EAU-Guidelines-on-Paediatric-Urology-2025_parent_0003', 'parent_index': 3, 'child_index': 1, 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 672}
------------------------------------------------------------------------------------------
. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_parent_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'parent_child_chunking', 'chunk_type': 'parent', 'parent_chunk_size': 2000, 'child_chunk_size': 1200, 'chunk_overlap': 100, 'character_count': 321}
------------------------------------------------------------------------------------------
. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.


### Resumen

In [ ]:
chunk_results_recursive = {
    "Recursive": recursive_chunks,
    "Recursive Fallback Token": recursive_token_chunks,
    "Parent Child": parent_child_chunks,
}


results_recursive = []

for method_name, method_chunks in chunk_results_recursive.items():
    lengths = [len(chunk.text) for chunk in method_chunks]

    results_recursive.append(
        {
            "Método": method_name,
            "Número de chunks": len(method_chunks),
            "Longitud mínima": min(lengths) if lengths else 0,
            "Longitud máxima": max(lengths) if lengths else 0,
            "Longitud media": (
                round(sum(lengths) / len(lengths), 2)
                if lengths
                else 0
            ),
        }
    )


results_recursive_df = pd.DataFrame(results_recursive)

results_recursive_df

,Método,Número de chunks,Longitud mínima,Longitud máxima,Longitud media
0,Recursive,35,487,1997,1665.66
1,Recursive Fallback Token,41,56,2167,1474.63
2,Parent Child,98,56,1997,1153.59

## Métodos semánticos

### Semantic Embedding Based Chunking
Utiliza SemanticChunker y embeddings para detectar puntos en los que cambia el significado y agrupa las frases semánticamente relacionadas

In [ ]:
semantic_embedding_chunking = SemanticEmbeddingChunker(
    embedding_model=(
        "sentence-transformers/all-MiniLM-L6-v2"
    ),
    breakpoint_threshold_type="percentile",
    breakpoint_threshold_amount=95.0,
    buffer_size=1,
)

semantic_embedding_chunks = semantic_embedding_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(
    f"Número total de chunks: "
    f"{len(semantic_embedding_chunks)}"
)

for chunk in semantic_embedding_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Número total de chunks: 52
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 166}
------------------------------------------------------------------------------------------
Schema version: 1.0. Document type: clinical_guideline. Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 2470}
------------------------------------------------------------------------------------------
Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 629}
------------------------------------------------------------------------------------------
Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 23}
------------------------------------------------------------------------------------------
Condition ref: cond_02.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 663}
------------------------------------------------------------------------------------------
Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 23}
------------------------------------------------------------------------------------------
Condition ref: cond_03.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 647}
------------------------------------------------------------------------------------------
Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 772}
------------------------------------------------------------------------------------------
Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 23}
------------------------------------------------------------------------------------------
Condition ref: cond_05.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 489}
------------------------------------------------------------------------------------------
Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 23}
------------------------------------------------------------------------------------------
Condition ref: cond_06.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 631}
------------------------------------------------------------------------------------------
Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 134}
------------------------------------------------------------------------------------------
Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0013
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 939}
------------------------------------------------------------------------------------------
Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0014
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 280}
------------------------------------------------------------------------------------------
Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0015
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_embedding_based_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'percentile', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 11103}
------------------------------------------------------------------------------------------

### Semantic Similarity Threshold Chunking
Genera embeddings por frase y compara el de cada frase con la anterior, cambiando de chunk cuando la similitud baja

In [ ]:
semantic_similarity_threshold_chunking = (
    SemanticSimilarityThresholdChunker(
        threshold=0.50,
        embedding_model=(
            "sentence-transformers/all-MiniLM-L6-v2"
        ),
    )
)

semantic_similarity_threshold_chunks = (
    semantic_similarity_threshold_chunking.chunk(
        text=document_text,
        doc_id=json_path.stem,
    )
)

print(
    f"Número total de chunks: "
    f"{len(semantic_similarity_threshold_chunks)}"
)

for chunk in semantic_similarity_threshold_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Número total de chunks: 860
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 20}
------------------------------------------------------------------------------------------
Schema version: 1.0.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 34}
------------------------------------------------------------------------------------------
Document type: clinical_guideline.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 9}
------------------------------------------------------------------------------------------
Metadata.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 2, 'mean_internal_similarity': 0.5609, 'character_count': 91}
------------------------------------------------------------------------------------------
Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 8}
------------------------------------------------------------------------------------------
Authors.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 17}
------------------------------------------------------------------------------------------
Name: C. Radmayr.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 12}
------------------------------------------------------------------------------------------
Role: Chair.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 17}
------------------------------------------------------------------------------------------
Name: G. Bogaert.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 17}
------------------------------------------------------------------------------------------
Role: Vice-chair.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 2, 'mean_internal_similarity': 0.6207, 'character_count': 32}
------------------------------------------------------------------------------------------
Name: A. Bujons. Name: B. Burgu.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 21}
------------------------------------------------------------------------------------------
Name: M. Castagnetti.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 10}
------------------------------------------------------------------------------------------
Name: L.A.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 8}
------------------------------------------------------------------------------------------
‘t Hoen.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0013
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 17}
------------------------------------------------------------------------------------------
Name: F. O’Kelly.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0014
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 10}
------------------------------------------------------------------------------------------
Name: N.A.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0015
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 12}
------------------------------------------------------------------------------------------
Pakkasjärvi.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0016
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 21}
------------------------------------------------------------------------------------------
Name: J. Quaedackers.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0017
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 12}
------------------------------------------------------------------------------------------
Name: Y.F.H.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0018
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 10}
------------------------------------------------------------------------------------------
Rawashdeh.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0019
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 10}
------------------------------------------------------------------------------------------
Name: M.S.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0020
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 6}
------------------------------------------------------------------------------------------
Silay.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0021
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 10}
------------------------------------------------------------------------------------------
Name: U.K.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0022
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 8}
------------------------------------------------------------------------------------------
Kennedy.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0023
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 27}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0024
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 15}
------------------------------------------------------------------------------------------
Name: M. Gnech.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0025
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 27}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0026
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 15}
------------------------------------------------------------------------------------------
Name: M. Skott.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0027
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 27}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0028
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 20}
------------------------------------------------------------------------------------------
Name: A. van Uitert.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0029
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 27}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0030
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 10}
------------------------------------------------------------------------------------------
Name: J.A.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0031
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 9}
------------------------------------------------------------------------------------------
Darraugh.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0032
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 24}
------------------------------------------------------------------------------------------
Role: Guidelines Office.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0033
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 11}
------------------------------------------------------------------------------------------
Year: 2025.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0034
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 18}
------------------------------------------------------------------------------------------
Language: English.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0035
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 20}
------------------------------------------------------------------------------------------
Audience: clinician.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0036
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_similarity_threshold_chunking', 'threshold': 0.5, 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sentence_count': 1, 'mean_internal_similarity': None, 'character_count': 30}
------------------------------------------------------------------------------------------

### Topic Based Chunking
Genera embeddings por frase y aplica clustering aglomerativo a las frases de temática similar, manteniendo el orden original

In [ ]:
topic_based_chunking = TopicBasedChunker(
    distance_threshold=0.50,
    embedding_model=(
        "sentence-transformers/all-MiniLM-L6-v2"
    ),
)

topic_based_chunks = topic_based_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(
    f"Número total de chunks: "
    f"{len(topic_based_chunks)}"
)

for chunk in topic_based_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Número total de chunks: 895
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 115, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Schema version: 1.0.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 125, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Document type: clinical_guideline.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 36, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Metadata.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 38, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Title: EAU Guidelines on Paediatric Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 139, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Organization: European Association of Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 10, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Authors.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 131, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: C. Radmayr.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Chair.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 14, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: G. Bogaert.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Vice-chair.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 64, 'sentence_count': 2}
------------------------------------------------------------------------------------------
Name: A. Bujons. Name: B. Burgu.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 166, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: M. Castagnetti.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 153, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: L.A. ‘t Hoen.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0013
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 77, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: F. O’Kelly.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0014
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 155, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: N.A.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0015
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 143, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Pakkasjärvi.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0016
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 149, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: J. Quaedackers.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0017
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 77, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: Y.F.H.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0018
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 101, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Rawashdeh.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0019
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 15, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: M.S.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0020
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 111, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Silay.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0021
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 83, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: U.K. Kennedy.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0022
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0023
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 14, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: M. Gnech.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0024
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0025
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 15, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: M. Skott.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0026
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0027
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 110, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: A. van Uitert.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0028
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Guidelines Associate.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0029
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 155, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Name: J.A.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0030
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 147, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Darraugh.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0031
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 35, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Role: Guidelines Office.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0032
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 163, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Year: 2025.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0033
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 89, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Language: English.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0034
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 150, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Audience: clinician.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0035
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 38, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Specialty: Paediatric Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0036
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 94, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Extraction date: 2025-04-10.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0037
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 107, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Quality flags: complex_tables_detected, truncated_sections.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0038
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 38, 'sentence_count': 2}
------------------------------------------------------------------------------------------
Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0039
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 120, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Scope.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0040
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 38, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0041
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 158, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Care settings: outpatient, inpatient, surgical, emergency.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0042
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 23, 'sentence_count': 1}
------------------------------------------------------------------------------------------
Target population: children, adolescents, neonates, infants.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0043
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 11, 'sentence_count': 2}
------------------------------------------------------------------------------------------
Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0044
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'topic_based_chunking', 'topic_label': 109, 'sentence_count': 1}

### Semantic Boundary Detection Chunking
Utiliza SemanticChunker y separa los chunks cuando hay cambios bruscos en la evolución de las distancias semánticas

In [ ]:
semantic_boundary_chunking = SemanticBoundaryChunker(
    embedding_model=(
        "sentence-transformers/all-MiniLM-L6-v2"
    ),
    breakpoint_threshold_amount=95.0,
    buffer_size=1,
)

semantic_boundary_chunks = semantic_boundary_chunking.chunk(
    text=document_text,
    doc_id=json_path.stem,
)

print(
    f"Número total de chunks: "
    f"{len(semantic_boundary_chunks)}"
)

for chunk in semantic_boundary_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Número total de chunks: 52
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 20}
------------------------------------------------------------------------------------------
Schema version: 1.0.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 136}
------------------------------------------------------------------------------------------
Document type: clinical_guideline. Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 3088}
------------------------------------------------------------------------------------------
Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 687}
------------------------------------------------------------------------------------------
Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 20}
------------------------------------------------------------------------------------------
Pathway id: path_03.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 626}
------------------------------------------------------------------------------------------
Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 20}
------------------------------------------------------------------------------------------
Pathway id: path_04.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 775}
------------------------------------------------------------------------------------------
Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 20}
------------------------------------------------------------------------------------------
Pathway id: path_05.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 492}
------------------------------------------------------------------------------------------
Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 554}
------------------------------------------------------------------------------------------
Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 244}
------------------------------------------------------------------------------------------
Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice. Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 939}
------------------------------------------------------------------------------------------
Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0013
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 280}
------------------------------------------------------------------------------------------
Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0014
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 793}
------------------------------------------------------------------------------------------
Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0015
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_boundary_detection', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'breakpoint_threshold_type': 'gradient', 'breakpoint_threshold_amount': 95.0, 'buffer_size': 1, 'character_count': 10304}
------------------------------------------------------------------------------------------

### Resumen

In [ ]:
chunk_results_semantic = {
    "Semantic Boundary Detection": semantic_boundary_chunks,
    "Semantic Embedding Based": semantic_embedding_chunks,
    "Semantic Similarity Threshold": semantic_similarity_threshold_chunks,
    "Topic Based": topic_based_chunks,
}


results_semantic = []

for method_name, method_chunks in chunk_results_semantic.items():
    lengths = [len(chunk.text) for chunk in method_chunks]

    results_semantic.append(
        {
            "Método": method_name,
            "Número de chunks": len(method_chunks),
            "Longitud mínima": min(lengths) if lengths else 0,
            "Longitud máxima": max(lengths) if lengths else 0,
            "Longitud media": (
                round(sum(lengths) / len(lengths), 2)
                if lengths
                else 0
            ),
        }
    )


results_semantic_df = pd.DataFrame(results_semantic)

results_semantic_df

,Método,Número de chunks,Longitud mínima,Longitud máxima,Longitud media
0,Semantic Boundary Detection,52,5,10304,1052.62
1,Semantic Embedding Based,52,20,11103,1052.62
2,Semantic Similarity Threshold,860,5,954,62.71
3,Topic Based,895,5,822,60.22

## Métodos dinámicos

### Content Density Adaptative Chunking
Divide en frases y agrupa según la densidad léxica (a mayor densidad mayor tamaño)

In [ ]:
content_density_adaptive_chunking = (
    ContentDensityAdaptiveChunker(
        base_chunk_size=2000,
    )
)

content_density_adaptive_chunks = (
    content_density_adaptive_chunking.chunk(
        text=document_text,
        doc_id=json_path.stem,
    )
)

print(
    f"Número total de chunks: "
    f"{len(content_density_adaptive_chunks)}"
)

for chunk in content_density_adaptive_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 55
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 1.0, 'mean_density_factor': 0.5, 'sentence_count': 42, 'character_count': 959}
------------------------------------------------------------------------------------------
Schema version: 1.0. Document type: clinical_guideline. Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.8745, 'mean_density_factor': 0.6255, 'sentence_count': 3, 'character_count': 1271}
------------------------------------------------------------------------------------------
It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9755, 'mean_density_factor': 0.5245, 'sentence_count': 13, 'character_count': 1014}
------------------------------------------------------------------------------------------
Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 1.0, 'mean_density_factor': 0.5, 'sentence_count': 13, 'character_count': 858}
------------------------------------------------------------------------------------------
Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9806, 'mean_density_factor': 0.5194, 'sentence_count': 14, 'character_count': 987}
------------------------------------------------------------------------------------------
Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9849, 'mean_density_factor': 0.5151, 'sentence_count': 14, 'character_count': 960}
------------------------------------------------------------------------------------------
Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9742, 'mean_density_factor': 0.5258, 'sentence_count': 15, 'character_count': 1000}
------------------------------------------------------------------------------------------
Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice. Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9923, 'mean_density_factor': 0.5077, 'sentence_count': 22, 'character_count': 985}
------------------------------------------------------------------------------------------
Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9938, 'mean_density_factor': 0.5062, 'sentence_count': 20, 'character_count': 958}
------------------------------------------------------------------------------------------
Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9931, 'mean_density_factor': 0.5069, 'sentence_count': 17, 'character_count': 1092}
------------------------------------------------------------------------------------------
Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9829, 'mean_density_factor': 0.5171, 'sentence_count': 15, 'character_count': 952}
------------------------------------------------------------------------------------------
Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML. Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.9908, 'mean_density_factor': 0.5092, 'sentence_count': 19, 'character_count': 936}
------------------------------------------------------------------------------------------
Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure. Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 1.0, 'mean_density_factor': 0.5, 'sentence_count': 16, 'character_count': 900}
------------------------------------------------------------------------------------------
Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0013
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'content_density_adaptive_chunking', 'base_chunk_size': 2000, 'mean_density': 0.988, 'mean_density_factor': 0.512, 'sentence_count': 14, 'character_count': 1007}
------------------------------------------------------------------------------------------

### Dynamic Token Size Chunking
Tokeniza y crea chunks de tamaño variable intentando separar por signos de puntuación o salto de línea

In [ ]:
dynamic_token_size_chunking = DynamicTokenSizeChunker(
    min_chunk_size=250,
    max_chunk_size=500,
    encoding_name="cl100k_base",
)

dynamic_token_size_chunks = (
    dynamic_token_size_chunking.chunk(
        text=document_text,
        doc_id=json_path.stem,
    )
)

print(
    f"Número total de chunks: "
    f"{len(dynamic_token_size_chunks)}"
)

for chunk in dynamic_token_size_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Número total de chunks: 26
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 0, 'end_token': 408, 'token_count': 408, 'character_count': 1572, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 408, 'end_token': 899, 'token_count': 491, 'character_count': 2536, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 899, 'end_token': 1386, 'token_count': 487, 'character_count': 2619, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 1386, 'end_token': 1881, 'token_count': 495, 'character_count': 2168, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 1881, 'end_token': 2370, 'token_count': 489, 'character_count': 2272, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 2370, 'end_token': 2867, 'token_count': 497, 'character_count': 2352, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Name: Buccal mucosa graft. Type: procedure. Mechanism: Use of buccal mucosa as a graft material in hypospadias repair, often for inlay grafts or staged repairs. Approved indications: Severe hypospadias requiring staged repairs, Primary repairs to reduce stenosis risk. Administration: Surgical procedure involving graft harvesting and placement. Key toxicities: Graft fibrosis.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'dynamic_token_size_chunking', 'min_chunk_size': 250, 'max_chunk_size': 500, 'encoding_name': 'cl100k_base', 'start_token': 2867, 'end_token': 3364, 'token_count': 497, 'character_count': 2443, 'split_reason': 'sentence_end'}
------------------------------------------------------------------------------------------
Name: Testosterone. Type: drug. Mechanism: Hormonal therapy used pre-operatively to increase penile size or glans circumference in hypospadias patients. Approved indications: Proximal hypospadias, Small appearing penis, Reduced glans circumference, Narrow urethral plate. Administration: Pre-operative administration, with cessation recommended 1-2 months prior to surgery. Key toxicities: Negative impact on wound-healing, Increased bleeding during surgery. Name: Anticholinergic agents. Type: drug. Mechanism: Medications that block acetylcholine receptors, used to treat overactive bladder symptoms. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as part of medical therapy. Name: Mirabegron. Type: drug. Mechanism: Beta-3 agonist that relaxes the bladder muscle, used for overactive bladder treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Oral administration as monotherapy or add-on therapy. Name: Transcutaneous electrical nerve stimulation (TENS). Type: procedure. Mechanism: Neuromodulation technique using electrical stimulation for urinary and faecal incontinence. Approved indications: Daytime lower urinary tract conditions. Administration: Non-invasive electrical stimulation therapy. Name: Percutaneous tibial nerve stimulation (PTNS). Type: procedure. Mechanism: Neuromodulation technique involving stimulation of the tibial nerve for incontinence treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Minimally invasive electrical stimulation therapy. Name: Sacral neuromodulation (SNM). Type: procedure. Mechanism: Neuromodulation technique involving implantation of a device to stimulate sacral nerves for bladder control. Approved indications: Daytime lower urinary tract conditions. Administration: Surgical implantation procedure. Name: Botulinum toxin A (BoNT-A). Type: drug. Mechanism: Neurotoxin used to relax muscles, injected for bladder overactivity treatment. Approved indications: Daytime lower urinary tract conditions. Administration: Cystoscopic injection into the bladder wall. Name: Trimethoprim. Type: drug. Mechanism: Antibacterial agent that inhibits bacterial folate synthesis. Approved indications: Antibacterial prophylaxis for urinary tract infections. Administration: Oral prophylactic dosage of 2 mg/kg body weight per day. Monitoring: Not recommended under 6 weeks of age.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007

### Semantic Variance Adaptative Chunking
Genera embeddings, calcula la similitud entre frases y corta el chunk cuando la similitud cae respecto a la media

In [ ]:
semantic_variance_adaptive_chunking = (
    SemanticVarianceAdaptiveChunker(
        sensitivity=0.15,
        embedding_model=(
            "sentence-transformers/all-MiniLM-L6-v2"
        ),
        window_size=3,
    )
)

semantic_variance_adaptive_chunks = (
    semantic_variance_adaptive_chunking.chunk(
        text=document_text,
        doc_id=json_path.stem,
    )
)

print(
    f"Número total de chunks: "
    f"{len(semantic_variance_adaptive_chunks)}"
)

for chunk in semantic_variance_adaptive_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Número total de chunks: 204
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0407, 'recent_mean_similarity': 0.2372, 'mean_internal_similarity': 0.2372, 'start_sentence_index': 0, 'end_sentence_index': 3, 'sentence_count': 3, 'character_count': 65}
------------------------------------------------------------------------------------------
Schema version: 1.0. Document type: clinical_guideline. Metadata.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.12, 'recent_mean_similarity': 0.2766, 'mean_internal_similarity': 0.5609, 'start_sentence_index': 3, 'end_sentence_index': 5, 'sentence_count': 2, 'character_count': 91}
------------------------------------------------------------------------------------------
Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.139, 'recent_mean_similarity': 0.4668, 'mean_internal_similarity': 0.3033, 'start_sentence_index': 5, 'end_sentence_index': 14, 'sentence_count': 9, 'character_count': 141}
------------------------------------------------------------------------------------------
Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0732, 'recent_mean_similarity': 0.2513, 'mean_internal_similarity': 0.1774, 'start_sentence_index': 14, 'end_sentence_index': 39, 'sentence_count': 25, 'character_count': 428}
------------------------------------------------------------------------------------------
‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.1161, 'recent_mean_similarity': 0.2715, 'mean_internal_similarity': 0.2715, 'start_sentence_index': 39, 'end_sentence_index': 43, 'sentence_count': 4, 'character_count': 833}
------------------------------------------------------------------------------------------
Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0418, 'recent_mean_similarity': 0.2722, 'mean_internal_similarity': None, 'start_sentence_index': 43, 'end_sentence_index': 44, 'sentence_count': 1, 'character_count': 6}
------------------------------------------------------------------------------------------
Scope.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0033, 'recent_mean_similarity': 0.3127, 'mean_internal_similarity': 0.2775, 'start_sentence_index': 44, 'end_sentence_index': 52, 'sentence_count': 8, 'character_count': 1088}
------------------------------------------------------------------------------------------
Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.123, 'recent_mean_similarity': 0.3373, 'mean_internal_similarity': 0.3802, 'start_sentence_index': 52, 'end_sentence_index': 58, 'sentence_count': 6, 'character_count': 587}
------------------------------------------------------------------------------------------
Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': -0.0017, 'recent_mean_similarity': 0.2012, 'mean_internal_similarity': 0.2403, 'start_sentence_index': 58, 'end_sentence_index': 61, 'sentence_count': 3, 'character_count': 65}
------------------------------------------------------------------------------------------
Pathway id: path_02. Condition ref: cond_02. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.1155, 'recent_mean_similarity': 0.4598, 'mean_internal_similarity': 0.4146, 'start_sentence_index': 61, 'end_sentence_index': 67, 'sentence_count': 6, 'character_count': 621}
------------------------------------------------------------------------------------------
Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.2735, 'recent_mean_similarity': 0.4592, 'mean_internal_similarity': None, 'start_sentence_index': 67, 'end_sentence_index': 68, 'sentence_count': 1, 'character_count': 20}
------------------------------------------------------------------------------------------
Pathway id: path_03.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0011
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0185, 'recent_mean_similarity': 0.2166, 'mean_internal_similarity': 0.2608, 'start_sentence_index': 68, 'end_sentence_index': 70, 'sentence_count': 2, 'character_count': 44}
------------------------------------------------------------------------------------------
Condition ref: cond_03. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0012
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.126, 'recent_mean_similarity': 0.3577, 'mean_internal_similarity': 0.7938, 'start_sentence_index': 70, 'end_sentence_index': 72, 'sentence_count': 2, 'character_count': 257}
------------------------------------------------------------------------------------------
Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0013
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.1621, 'recent_mean_similarity': 0.5519, 'mean_internal_similarity': 0.5519, 'start_sentence_index': 72, 'end_sentence_index': 76, 'sentence_count': 4, 'character_count': 323}
------------------------------------------------------------------------------------------
Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0014
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.2898, 'recent_mean_similarity': 0.5332, 'mean_internal_similarity': None, 'start_sentence_index': 76, 'end_sentence_index': 77, 'sentence_count': 1, 'character_count': 20}
------------------------------------------------------------------------------------------
Pathway id: path_04.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0015
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0106, 'recent_mean_similarity': 0.2461, 'mean_internal_similarity': 0.2864, 'start_sentence_index': 77, 'end_sentence_index': 79, 'sentence_count': 2, 'character_count': 44}
------------------------------------------------------------------------------------------
Condition ref: cond_04. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0016
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.1114, 'recent_mean_similarity': 0.4336, 'mean_internal_similarity': 0.3944, 'start_sentence_index': 79, 'end_sentence_index': 87, 'sentence_count': 8, 'character_count': 730}
------------------------------------------------------------------------------------------
Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0017
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0077, 'recent_mean_similarity': 0.2095, 'mean_internal_similarity': 0.2585, 'start_sentence_index': 87, 'end_sentence_index': 90, 'sentence_count': 3, 'character_count': 65}
------------------------------------------------------------------------------------------
Pathway id: path_05. Condition ref: cond_05. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0018
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.0411, 'recent_mean_similarity': 0.335, 'mean_internal_similarity': 0.4214, 'start_sentence_index': 90, 'end_sentence_index': 95, 'sentence_count': 5, 'character_count': 447}
------------------------------------------------------------------------------------------
Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0019
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': -0.0139, 'recent_mean_similarity': 0.1809, 'mean_internal_similarity': 0.2508, 'start_sentence_index': 95, 'end_sentence_index': 98, 'sentence_count': 3, 'character_count': 65}
------------------------------------------------------------------------------------------
Pathway id: path_06. Condition ref: cond_06. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0020
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'semantic_variance_adaptive_chunking', 'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2', 'sensitivity': 0.15, 'window_size': 3, 'split_similarity': 0.1916, 'recent_mean_similarity': 0.4176, 'mean_internal_similarity': 0.6333, 'start_sentence_index': 98, 'end_sentence_index': 101, 'sentence_count': 3, 'character_count': 290}
------------------------------------------------------------------------------------------

### Resumen

In [ ]:
chunk_results_dynamic = {
    "Content Density Adaptative": content_density_adaptive_chunks,
    "Dynamic Token Size": dynamic_token_size_chunks,
    "Semantic Variance Adaptative": semantic_variance_adaptive_chunks,
}


results_dynamic = []

for method_name, method_chunks in chunk_results_dynamic.items():
    lengths = [len(chunk.text) for chunk in method_chunks]

    results_dynamic.append(
        {
            "Método": method_name,
            "Número de chunks": len(method_chunks),
            "Longitud mínima": min(lengths) if lengths else 0,
            "Longitud máxima": max(lengths) if lengths else 0,
            "Longitud media": (
                round(sum(lengths) / len(lengths), 2)
                if lengths
                else 0
            ),
        }
    )


results_dynamic_df = pd.DataFrame(results_dynamic)

results_dynamic_df

,Método,Número de chunks,Longitud mínima,Longitud máxima,Longitud media
0,Content Density Adaptative,55,771,1279,995.15
1,Dynamic Token Size,26,1136,2619,2106.73
2,Semantic Variance Adaptative,204,6,4578,267.57

## Métodos basados en LLM

### LLM Boundary Detection Chunking
Genera chunks provisionales con reglas simples y si detecta tamaños desiguales, un LLM reajusta las posiciones de corte. Añade overlap

In [ ]:
llm_boundary_detection_chunking = (
    LLMBoundaryDetectionChunker(
        max_chars=2000,
        overlap=200,
        enable_llm_refinement=True,
        llm_timeout_sec=15.0,
        llm_max_tokens=256,
        llm_temperature=0.0,
    )
)

llm_boundary_detection_chunks = (
    llm_boundary_detection_chunking.chunk(
        text=document_text,
        doc_id=json_path.stem,
    )
)

print(
    f"Número total de chunks: "
    f"{len(llm_boundary_detection_chunks)}"
)

for chunk in llm_boundary_detection_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
[transformers] If you want to use `BertLMHeadModel` as a standalone, add `is_decoder=True.`

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

[transformers] This checkpoint seem corrupted. The tied weights mapping for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are absent from the checkpoint, and we could not find another related tied weight for those keys
[transformers] BertLMHeadModel LOAD REPORT from: ./models/sentence-transformers__all-MiniLM-L6-v2
Key                                        | Status     |
-------------------------------------------+------------+-
pooler.dense.weight                        | UNEXPECTED |
pooler.dense.bias                          | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | MISSING    |
cls.predictions.bias                       | MISSING    |
cls.predictions.transform.dense.bias       | MISSING    |
cls.predictions.transform.LayerNorm.weight | MISSING    |
cls.predictions.transform.dense.weight     | MISSING    |
cls.predictions.decoder.bias               | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Número total de chunks: 29
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 1569, 'used_llm_refinement': False, 'chunk_index': 0}
------------------------------------------------------------------------------------------
Schema version: 1.0. Document type: clinical_guideline. Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 2074, 'used_llm_refinement': False, 'chunk_index': 1}
------------------------------------------------------------------------------------------
disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology. Scope.

Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management. Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 2191, 'used_llm_refinement': False, 'chunk_index': 2}
------------------------------------------------------------------------------------------
id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves.

Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates. Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 1998, 'used_llm_refinement': False, 'chunk_index': 3}
------------------------------------------------------------------------------------------
Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line.

Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens. Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice. Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 2153, 'used_llm_refinement': False, 'chunk_index': 4}
------------------------------------------------------------------------------------------
30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general.

Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%. Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 2145, 'used_llm_refinement': False, 'chunk_index': 5}
------------------------------------------------------------------------------------------
explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor.

Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia. Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML. Therapies index. Name: TIP urethroplasty. Type: procedure. Mechanism: Surgical technique for urethral reconstruction in hypospadias repair, involving tubularisation of the urethral plate after midline incision. Approved indications: Distal hypospadias, Mid-penile hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 2168, 'used_llm_refinement': False, 'chunk_index': 6}
------------------------------------------------------------------------------------------
Fistula, Meatal stenosis, Recurrent penile curvature, Urethral stricture. Monitoring: Post-operative wound care, Uroflow assessments during follow-up. Name: Mathieu technique. Type: procedure.

Mechanism: Surgical technique for hypospadias repair using a flap-based approach. Approved indications: Distal hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Fistula. Name: Thiersch-Duplay technique. Type: procedure. Mechanism: Surgical technique for urethral reconstruction by tubularising a wide urethral plate. Approved indications: Hypospadias with wide urethral plate. Administration: Surgical procedure performed under anesthesia. Name: Onlay technique. Type: procedure. Mechanism: Surgical technique using a preputial island flap for urethral reconstruction. Approved indications: Proximal hypospadias, Hypospadias with unsuitable urethral plate for tubularisation. Administration: Surgical procedure performed under anesthesia. Name: Duckett tube. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair using a tubularised flap. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Koyanagi-Hayashi technique. Type: procedure. Mechanism: Single-stage surgical technique for hypospadias repair. Approved indications: Hypospadias where urethral plate continuity cannot be preserved. Administration: Surgical procedure performed under anesthesia. Name: Nesbit plication. Type: procedure. Mechanism: Surgical technique for penile curvature correction by dorsal shortening, with or without excision of tunica albuginea. Approved indications: Penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia. Key toxicities: Penile shortening, Decreased sensitivity. Name: Ventral lengthening. Type: procedure. Mechanism: Surgical technique for penile curvature correction by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_boundary_detection_chunking', 'max_chars': 2000, 'overlap': 200, 'character_count': 2167, 'used_llm_refinement': False, 'chunk_index': 7}
------------------------------------------------------------------------------------------
by ventral lengthening of the corpora, using corporotomy techniques. Approved indications: Severe penile curvature in hypospadias. Administration: Surgical procedure performed under anesthesia.


### LLM Segment Then Chunk
Segmenta el documento por estructura y envía al LLM los segmentos grandes o ambiguos para subdividirlos

In [ ]:
llm_segment_then_chunking = LLMSegmentThenChunker(
    max_chars=2000,
    overlap=200,
    llm_refine_threshold=1200,
    enable_llm_refinement=True,
    llm_timeout_sec=15.0,
    llm_max_tokens=256,
    llm_temperature=0.0,
)

llm_segment_then_chunks = (
    llm_segment_then_chunking.chunk(
        text=document_text,
        doc_id=json_path.stem,
    )
)

print(
    f"Número total de chunks: "
    f"{len(llm_segment_then_chunks)}"
)

for chunk in llm_segment_then_chunks:
    print("=" * 90)
    print(f"Chunk ID: {chunk.chunk_id}")
    print(f"Documento: {chunk.doc_id}")
    print(f"Metadatos: {chunk.metadata}")
    print("-" * 90)
    print(chunk.text)
    print()

[transformers] If you want to use `BertLMHeadModel` as a standalone, add `is_decoder=True.`

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

[transformers] This checkpoint seem corrupted. The tied weights mapping for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are absent from the checkpoint, and we could not find another related tied weight for those keys
[transformers] BertLMHeadModel LOAD REPORT from: ./models/sentence-transformers__all-MiniLM-L6-v2
Key                                        | Status     |
-------------------------------------------+------------+-
pooler.dense.weight                        | UNEXPECTED |
pooler.dense.bias                          | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | MISSING    |
cls.predictions.bias                       | MISSING    |
cls.predictions.transform.dense.bias       | MISSING    |
cls.predictions.transform.LayerNorm.weight | MISSING    |
cls.predictions.transform.dense.weight     | MISSING    |
cls.predictions.decoder.bias               | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Número total de chunks: 37
==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0000
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 0, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 0, 'character_count': 20}
------------------------------------------------------------------------------------------
Schema version: 1.0.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0001
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 1, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 1, 'character_count': 56}
------------------------------------------------------------------------------------------
Schema version: 1.0.

Document type: clinical_guideline.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0002
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 2, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 2, 'character_count': 1542}
------------------------------------------------------------------------------------------
Document type: clinical_guideline.

Metadata. Title: EAU Guidelines on Paediatric Urology. Organization: European Association of Urology. Authors. Name: C. Radmayr. Role: Chair. Name: G. Bogaert. Role: Vice-chair. Name: A. Bujons. Name: B. Burgu. Name: M. Castagnetti. Name: L.A. ‘t Hoen. Name: F. O’Kelly. Name: N.A. Pakkasjärvi. Name: J. Quaedackers. Name: Y.F.H. Rawashdeh. Name: M.S. Silay. Name: U.K. Kennedy. Role: Guidelines Associate. Name: M. Gnech. Role: Guidelines Associate. Name: M. Skott. Role: Guidelines Associate. Name: A. van Uitert. Role: Guidelines Associate. Name: J.A. Darraugh. Role: Guidelines Office. Year: 2025. Language: English. Audience: clinician. Specialty: Paediatric Urology. Extraction date: 2025-04-10. Quality flags: complex_tables_detected, truncated_sections. Summary: This guideline provides evidence-based recommendations for the diagnosis and management of various paediatric urological conditions. It covers a wide range of topics including phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, lower urinary tract conditions, nocturnal enuresis, spinal dysraphism, upper urinary tract dilatation, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0003
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 3, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 3, 'character_count': 1210}
------------------------------------------------------------------------------------------
duplication, disorders of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, trauma, peri-operative management, laparoscopic surgery, and transitional urology.

Scope. Conditions covered: phimosis, undescended testes, testicular tumours, fertility preservation, hydrocele, acute scrotum, hypospadias, congenital penile curvature, varicocele, urinary tract infections, day-time lower urinary tract conditions, monosymptomatic nocturnal enuresis, spinal dysraphism, dilatation of the upper urinary tract, vesicoureteric reflux, urinary stone disease, obstructive pathology of renal duplication, disorders/differences of sex development, congenital lower urinary tract obstruction, rare conditions, emergencies, paediatric urological trauma, peri-operative management, basic principles of laparoscopic surgery, transitional urology. Care settings: outpatient, inpatient, surgical, emergency. Target population: children, adolescents, neonates, infants. Therapeutic areas: medical therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0004
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 4, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 4, 'character_count': 2052}
------------------------------------------------------------------------------------------
therapy, surgical therapy, antibiotic prophylaxis, hormonal therapy, urotherapy, neuromodulation, laparoscopic surgery, robotic-assisted surgery, endoscopic procedures, radiological management.

Treatment pathways. Pathway id: path_01. Condition ref: cond_01. Setting: first_line. Patient population: Boys with physiological phimosis and history of urinary tract infection. Decision rules: Use topical steroid cream for physiological phimosis to reduce recurrent urinary tract infections. Recommended regimens. Name: Topical steroid cream. Summary: Application of steroid cream to treat physiological phimosis in boys with urinary tract infections to lower recurrence risk. Special considerations: The number needed to treat to prevent a single urinary tract infection is high in patients without associated urinary tract abnormalities, questioning cost-benefit ratio. Pathway id: path_02. Condition ref: cond_02. Setting: first_line. Patient population: Children with urinary tract infections and underlying urological conditions, particularly posterior urethral valves. Decision rules: Consider circumcision for preventing urinary tract infection recurrences in patients with underlying urological conditions. Recommended regimens. Name: Circumcision. Summary: Surgical removal of the foreskin to reduce recurrent urinary tract infections in children with specific urological conditions. Special considerations: Circumcision appears more cost-effective for preventing urinary tract infection recurrences in patients with underlying urological conditions. Pathway id: path_03. Condition ref: cond_03. Setting: first_line. Patient population: Toilet-trained children with urinary tract infections and bladder bowel dysfunction. Decision rules: Screen for bladder bowel dysfunction in toilet-trained children with febrile or recurrent urinary tract infections and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0005
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 4, 'segment_part_index': 1, 'used_llm_refinement': False, 'chunk_index': 5, 'character_count': 2036}
------------------------------------------------------------------------------------------
and treat if present. Recommended regimens. Name: Treatment of bladder bowel dysfunction. Summary: Management of bladder and bowel dysfunction to lower urinary tract infection recurrence rates.

Special considerations: Treatment of constipation leads to a decrease in urinary tract infection recurrence; multidisciplinary approach is recommended. Pathway id: path_04. Condition ref: cond_04. Setting: first_line. Patient population: Children with urinary tract infections and normal urinary tract anatomy. Decision rules: Consider non-antibiotic prophylactic measures like cranberry products or probiotics to prevent urinary tract infection recurrence. Recommended regimens. Name: Cranberry products. Summary: Use of cranberry-based interventions to reduce risk of urinary tract infection recurrence in children with normal urinary tracts. Name: Probiotics. Summary: Administration of probiotic supplements to lower urinary tract infection recurrence risk in children with normal urogenital anatomy. Special considerations: Quality of evidence is moderate for cranberry products; evidence for probiotics needs strengthening with larger trials. Pathway id: path_05. Condition ref: cond_05. Setting: first_line. Patient population: Children with acute pyelonephritis. Decision rules: Consider Vitamin A supplementation to prevent renal scarring in children with acute pyelonephritis. Recommended regimens. Name: Vitamin A. Summary: Supplementation with Vitamin A to reduce risk of renal scarring in pediatric patients with acute pyelonephritis. Special considerations: Vitamin A has shown promising results but is not yet recommended for routine clinical use. Pathway id: path_06. Condition ref: cond_06. Setting: first_line. Patient population: Patients with recurrent urinary tract infections and vitamin D deficiency. Biomarker condition: Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0006
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 4, 'segment_part_index': 2, 'used_llm_refinement': False, 'chunk_index': 6, 'character_count': 495}
------------------------------------------------------------------------------------------
Vitamin D deficiency. Decision rules: Consider vitamin D treatment for preventing renal scarring in patients with recurrent urinary tract infections and vitamin D deficiency. Recommended regimens.

Name: Vitamin D. Summary: Supplementation with vitamin D to potentially prevent renal scarring in individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0007
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 5, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 7, 'character_count': 2184}
------------------------------------------------------------------------------------------
individuals with recurrent urinary tract infections and vitamin D deficiency. Special considerations: No prospective studies have been conducted; not recommended for routine use in clinical practice.

Safety. Toxicities. Event: subfertility. Incidence: 36-39%. Recognition: reduced spermatogenesis, abnormal semen analysis. Management. Severity: general. Actions: Early surgical intervention (mean torsion time less than thirteen hours) with detorsion is recommended to preserve fertility; prolonged torsion period (mean 70 hours) followed by orchiectomy increases risk of fertility impairment. Prevention: urgent surgical exploration for testicular torsion. Event: testicular atrophy. Incidence: 30%. Recognition: reduced testicular size after mumps orchitis. Event: urethral fistula. Incidence: 5% to 50%. Recognition: urinary leakage from surgical site. Management. Severity: general. Actions: Use techniques to minimize incidence, such as adequate dissection, good tissue handling, and sufficient covering of urethral reconstruction with tunica vaginalis or double-layer dartos fascia. Prevention: use of flaps for additional coverage of neourethra. Event: meatal stenosis. Incidence: 5% to 15%. Recognition: narrowing of urethral meatus, urinary obstruction. Management. Severity: general. Actions: Use inlay grafts to reduce risk by 66% compared to TIP alone; avoid reconstruction under tension. Prevention: use of inlay grafts. Event: urethral stricture. Incidence: 8% to 13%. Recognition: narrowing of urethra, obstructive urinary flow. Management. Severity: general. Actions: May require further surgical intervention, especially in proximal hypospadias repairs. Event: recurrent penile curvature. Incidence: 5% vs 25% (ventral lengthening vs dorsoplication). Recognition: persistent ventral curvature of penis. Management. Severity: general. Actions: Consider ventral lengthening techniques (e.g., multiple transverse corporotomies) over dorsoplication to reduce recurrence; additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0008
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 5, 'segment_part_index': 1, 'used_llm_refinement': False, 'chunk_index': 8, 'character_count': 2195}
------------------------------------------------------------------------------------------
additional surgeries may be needed during puberty. Prevention: use of ventral lengthening techniques, staged repairs for proximal hypospadias. Event: glans and wound dehiscence. Incidence: 9% to 17%.

Recognition: separation of glans or surgical wound. Event: graft fibrosis. Incidence: more than one-third. Recognition: fibrosis in buccal mucosa grafts. Prophylaxis. Type: antibacterial. Recommendation: Use antibacterial prophylaxis for urinary tract infections (UTIs) in children. Target population: children with UTIs. Type: antiviral. Recommendation: Not explicitly mentioned; no specific antiviral prophylaxis recommended. Type: antifungal. Recommendation: Not explicitly mentioned; no specific antifungal prophylaxis recommended. Type: antiemetic. Recommendation: Not explicitly mentioned; no specific antiemetic prophylaxis recommended. Type: growth_factor. Recommendation: Not explicitly mentioned; no specific growth factor prophylaxis recommended. Type: tumor_lysis_syndrome. Recommendation: Not explicitly mentioned; no specific tumor lysis syndrome prophylaxis recommended. Type: thromboprophylaxis. Recommendation: Not explicitly mentioned; no specific thromboprophylaxis recommended. Type: other. Recommendation: Use non-antibiotic measures such as cranberry products and probiotics to reduce UTI recurrence in children with normal urinary tract. Target population: children with UTIs and normal urinary tract. Type: other. Recommendation: Consider steroid cream for physiologic phimosis in boys with UTIs to reduce recurrences. Target population: boys with physiologic phimosis and UTIs. Type: other. Recommendation: Treat bladder and bowel dysfunction (BBD) and lower urinary tract disorders to lower UTI recurrence rates. Target population: toilet-trained children with UTIs. Infection management. Pathogen or syndrome: urinary tract infection (UTI). Prevention: antibacterial prophylaxis, cranberry products, probiotics, steroid cream for phimosis, treatment of BBD and lower urinary tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0009
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 5, 'segment_part_index': 2, 'used_llm_refinement': False, 'chunk_index': 9, 'character_count': 260}
------------------------------------------------------------------------------------------
tract disorders, adequate hydration, proper hygiene, optimisation of bladder emptying, correct catheterisation techniques. Management: not specified. Pathogen or syndrome: febrile neutropenia.

Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.

==========================================================================================
Chunk ID: EAU-Guidelines-on-Paediatric-Urology-2025_chunk_0010
Documento: EAU-Guidelines-on-Paediatric-Urology-2025
Metadatos: {'chunker': 'llm_segment_then_chunking', 'max_chars': 2000, 'overlap': 200, 'llm_refine_threshold': 1200, 'unit_type': 'structured_paragraph', 'source_segment_index': 6, 'segment_part_index': 0, 'used_llm_refinement': False, 'chunk_index': 10, 'character_count': 1985}
------------------------------------------------------------------------------------------
Pathogen or syndrome: HBV reactivation. Pathogen or syndrome: PML.


### Resumen

In [ ]:
chunk_results_llm = {
    "LLM Boundary Detection": llm_boundary_detection_chunks,
    "LLM Segment Then Chunk": llm_segment_then_chunks,
}


results_llm = []

for method_name, method_chunks in chunk_results_llm.items():
    lengths = [len(chunk.text) for chunk in method_chunks]

    results_llm.append(
        {
            "Método": method_name,
            "Número de chunks": len(method_chunks),
            "Longitud mínima": min(lengths) if lengths else 0,
            "Longitud máxima": max(lengths) if lengths else 0,
            "Longitud media": (
                round(sum(lengths) / len(lengths), 2)
                if lengths
                else 0
            ),
        }
    )


results_llm_df = pd.DataFrame(results_llm)

results_llm_df

,Método,Número de chunks,Longitud mínima,Longitud máxima,Longitud media
0,LLM Boundary Detection,29,952,2196,2076.48
1,LLM Segment Then Chunk,37,20,2200,1659.19

## Resumen global

In [34]:
import pandas as pd
import numpy as np


# Separamos parent y child para no mezclar
# dos niveles distintos de chunking
parent_chunks = [
    chunk
    for chunk in parent_child_chunks
    if chunk.metadata.get("chunk_type") == "parent"
]

child_chunks = [
    chunk
    for chunk in parent_child_chunks
    if chunk.metadata.get("chunk_type") == "child"
]


chunk_results = {
    "Fixed Character": fixed_character_chunks,
    "Fixed Token": fixed_token_chunks,
    "Length Aware": length_aware_chunks,
    "Overlapping Token": overlapping_token_chunks,
    "Paragraph Based": paragraph_based_chunks,
    "Paragraph Group": paragraph_group_chunks,
    "Sentence Based": sentence_based_chunks,
    "Sentence Group": sentence_group_chunks,
    "Sliding Window Token": sliding_window_token_chunks,
    "Recursive": recursive_chunks,
    "Recursive Fallback Token": recursive_token_chunks,
    "Parent Child - Parent": parent_chunks,
    "Parent Child - Child": child_chunks,
    "Semantic Boundary Detection": semantic_boundary_chunks,
    "Semantic Embedding Based": semantic_embedding_chunks,
    "Semantic Similarity Threshold": (
        semantic_similarity_threshold_chunks
    ),
    "Topic Based": topic_based_chunks,
    "Content Density Adaptive": (
        content_density_adaptive_chunks
    ),
    "Dynamic Token Size": dynamic_token_size_chunks,
    "Semantic Variance Adaptive": (
        semantic_variance_adaptive_chunks
    ),
    "LLM Boundary Detection": (
        llm_boundary_detection_chunks
    ),
    "LLM Segment Then Chunk": (
        llm_segment_then_chunks
    ),
}


original_character_count = len(document_text)

results = []


for method_name, method_chunks in chunk_results.items():

    texts = [
        chunk.text.strip()
        for chunk in method_chunks
        if chunk.text and chunk.text.strip()
    ]

    lengths = [
        len(text)
        for text in texts
    ]

    if not lengths:
        results.append(
            {
                "Método": method_name,
                "Número de chunks": 0,
                "Caracteres mínimos": 0,
                "Caracteres P25": 0,
                "Caracteres mediana": 0,
                "Caracteres medios": 0,
                "Caracteres P75": 0,
                "Caracteres máximos": 0,
                "Desviación estándar": 0,
                "Chunks < 400 caracteres (%)": 0,
                "Caracteres totales": 0,
                "Ratio caracteres/original": 0,
            }
        )
        continue

    small_chunks = sum(
        length < 400
        for length in lengths
    )

    total_characters = sum(lengths)

    results.append(
        {
            "Método": method_name,
            "Número de chunks": len(lengths),

            "Caracteres mínimos": min(lengths),

            "Caracteres P25": round(
                np.percentile(lengths, 25),
                2,
            ),

            "Caracteres mediana": round(
                np.median(lengths),
                2,
            ),

            "Caracteres medios": round(
                np.mean(lengths),
                2,
            ),

            "Caracteres P75": round(
                np.percentile(lengths, 75),
                2,
            ),

            "Caracteres máximos": max(lengths),

            "Desviación estándar": round(
                np.std(lengths),
                2,
            ),

            "Chunks < 400 caracteres (%)": round(
                small_chunks / len(lengths) * 100,
                2,
            ),

            "Caracteres totales": total_characters,

            "Ratio caracteres/original": round(
                total_characters
                / original_character_count,
                3,
            )
            if original_character_count > 0
            else 0,
        }
    )


results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Caracteres mediana",
    ascending=True,
).reset_index(drop=True)

results_df

,Método,Número de chunks,Caracteres mínimos,Caracteres P25,Caracteres mediana,Caracteres medios,Caracteres P75,Caracteres máximos,Desviación estándar,Chunks < 400 caracteres (%),Caracteres totales,Ratio caracteres/original
0,Semantic Similarity Threshold,860,5,15.00,21.0,62.71,66.75,954,98.45,98.60,53928,0.984
1,Topic Based,895,5,15.00,21.0,60.22,69.00,822,87.68,98.99,53893,0.983
2,Sentence Based,990,5,16.00,25.0,54.34,80.75,661,60.88,99.70,53798,0.982
3,Semantic Variance Adaptive,204,6,44.00,158.0,267.57,320.75,4578,413.42,78.43,54584,0.996
4,Semantic Boundary Detection,52,5,19.25,262.0,1052.62,940.00,10304,1962.58,55.77,54736,0.999
5,Semantic Embedding Based,52,20,33.00,270.5,1052.62,1029.25,11103,1989.14,51.92,54736,0.999
6,Parent Child - Child,63,56,774.50,917.0,906.95,1158.00,1199,278.93,6.35,57138,1.043
7,Content Density Adaptive,55,771,955.00,987.0,995.15,1009.00,1279,89.34,0.00,54733,0.999
8,Sentence Group,55,338,396.50,1091.0,1106.45,1528.00,2326,604.68,25.45,60855,1.110
9,Recursive Fallback Token,41,56,1009.00,1692.0,1474.63,1801.00,2167,506.62,2.44,60460,1.103
10,Parent Child - Parent,35,138,1497.50,1884.0,1597.54,1983.50,1997,561.71,5.71,55914,1.020
11,Recursive,35,487,1734.50,1884.0,1665.66,1962.00,1997,483.81,0.00,58298,1.064
12,Fixed Character,31,799,2000.00,2000.0,1961.10,2000.00,2000,212.17,0.00,60794,1.109
13,Length Aware,28,522,1987.75,2028.0,1955.71,2055.25,2069,290.50,0.00,54760,0.999
14,LLM Segment Then Chunk,37,20,1210.00,2036.0,1659.19,2172.00,2200,707.64,8.11,61390,1.120
15,Paragraph Based,14,20,1133.25,2130.0,3912.43,4217.50,19809,4943.47,14.29,54774,1.000
16,LLM Boundary Detection,29,952,2093.00,2157.0,2076.48,2183.00,2196,243.47,0.00,60218,1.099
17,Dynamic Token Size,26,1136,2077.00,2255.5,2106.73,2348.25,2619,413.10,0.00,54775,1.000
18,Overlapping Token,30,822,2084.75,2309.5,2151.20,2406.25,2722,452.31,0.00,64536,1.178
19,Fixed Token,30,822,2084.75,2309.5,2151.20,2406.25,2722,452.31,0.00,64536,1.178
20,Sliding Window Token,30,822,2084.75,2309.5,2151.20,2406.25,2722,452.31,0.00,64536,1.178
21,Paragraph Group,7,1564,5640.00,7778.0,13506.71,20257.50,33410,10804.46,0.00,94547,1.725

In [32]:
import pandas as pd
import numpy as np
import tiktoken


# Tokenizador común para comparar todos los métodos
encoding = tiktoken.get_encoding("cl100k_base")


# Separamos parent y child para no mezclar dos niveles distintos
parent_chunks = [
    chunk
    for chunk in parent_child_chunks
    if chunk.metadata.get("chunk_type") == "parent"
]

child_chunks = [
    chunk
    for chunk in parent_child_chunks
    if chunk.metadata.get("chunk_type") == "child"
]


chunk_results = {
    "Fixed Character": fixed_character_chunks,
    "Fixed Token": fixed_token_chunks,
    "Length Aware": length_aware_chunks,
    "Overlapping Token": overlapping_token_chunks,
    "Paragraph Based": paragraph_based_chunks,
    "Paragraph Group": paragraph_group_chunks,
    "Sentence Based": sentence_based_chunks,
    "Sentence Group": sentence_group_chunks,
    "Sliding Window Token": sliding_window_token_chunks,
    "Recursive": recursive_chunks,
    "Recursive Fallback Token": recursive_token_chunks,
    "Parent Child - Parent": parent_chunks,
    "Parent Child - Child": child_chunks,
    "Semantic Boundary Detection": semantic_boundary_chunks,
    "Semantic Embedding Based": semantic_embedding_chunks,
    "Semantic Similarity Threshold": semantic_similarity_threshold_chunks,
    "Topic Based": topic_based_chunks,
    "Content Density Adaptive": content_density_adaptive_chunks,
    "Dynamic Token Size": dynamic_token_size_chunks,
    "Semantic Variance Adaptive": semantic_variance_adaptive_chunks,
    "LLM Boundary Detection": llm_boundary_detection_chunks,
    "LLM Segment Then Chunk": llm_segment_then_chunks,
}


original_token_count = len(
    encoding.encode(document_text)
)

results = []


for method_name, method_chunks in chunk_results.items():

    # Eliminamos posibles chunks vacíos
    texts = [
        chunk.text.strip()
        for chunk in method_chunks
        if chunk.text and chunk.text.strip()
    ]

    character_lengths = [
        len(text)
        for text in texts
    ]

    token_lengths = [
        len(encoding.encode(text))
        for text in texts
    ]

    if not texts:
        results.append(
            {
                "Método": method_name,
                "Número de chunks": 0,
            }
        )
        continue

    total_tokens = sum(token_lengths)

    small_chunks = sum(
        token_count < 100
        for token_count in token_lengths
    )

    results.append(
        {
            "Método": method_name,
            "Número de chunks": len(texts),

            "Caracteres mínimos": min(
                character_lengths
            ),
            "Caracteres máximos": max(
                character_lengths
            ),
            "Caracteres medios": round(
                np.mean(character_lengths),
                2,
            ),

            "Tokens mínimos": min(
                token_lengths
            ),
            "Tokens P25": round(
                np.percentile(token_lengths, 25),
                2,
            ),
            "Tokens mediana": round(
                np.median(token_lengths),
                2,
            ),
            "Tokens medios": round(
                np.mean(token_lengths),
                2,
            ),
            "Tokens P75": round(
                np.percentile(token_lengths, 75),
                2,
            ),
            "Tokens máximos": max(
                token_lengths
            ),
            "Desviación tokens": round(
                np.std(token_lengths),
                2,
            ),

            "Chunks < 100 tokens (%)": round(
                small_chunks / len(texts) * 100,
                2,
            ),

            "Tokens totales": total_tokens,

            "Ratio tokens/original": round(
                total_tokens / original_token_count,
                3,
            )
            if original_token_count > 0
            else 0,
        }
    )


results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Tokens mediana",
    ascending=True,
).reset_index(drop=True)

results_df

,Método,Número de chunks,Caracteres mínimos,Caracteres máximos,Caracteres medios,Tokens mínimos,Tokens P25,Tokens mediana,Tokens medios,Tokens P75,Tokens máximos,Desviación tokens,Chunks < 100 tokens (%),Tokens totales,Ratio tokens/original
0,Semantic Similarity Threshold,860,5,954,62.71,2,6.00,7.0,14.81,14.25,199,20.05,98.84,12740,1.014
1,Topic Based,895,5,822,60.22,2,6.00,7.0,14.24,15.00,212,17.98,99.11,12745,1.014
2,Sentence Based,990,5,661,54.34,2,7.00,8.0,12.88,17.00,142,12.28,99.60,12754,1.015
3,Semantic Variance Adaptive,204,6,4578,267.57,2,11.00,36.0,61.63,67.00,1730,131.74,81.86,12572,1.000
4,Semantic Boundary Detection,52,5,10304,1052.62,2,7.00,62.5,241.67,207.75,2162,453.54,57.69,12567,1.000
5,Semantic Embedding Based,52,20,11103,1052.62,7,12.00,65.0,241.63,218.25,2344,459.54,51.92,12565,1.000
6,Parent Child - Child,63,56,1199,906.95,15,165.50,210.0,209.29,252.00,485,82.33,6.35,13185,1.049
7,Content Density Adaptive,55,771,1279,995.15,157,198.00,216.0,228.56,230.00,408,52.47,0.00,12571,1.000
8,Sentence Group,55,338,2326,1106.45,107,149.00,238.0,254.40,321.00,524,108.41,0.00,13992,1.113
9,Recursive Fallback Token,41,56,2167,1474.63,15,372.00,384.0,339.61,393.00,399,99.27,2.44,13924,1.108
10,Recursive,35,487,1997,1665.66,86,350.50,404.0,382.94,433.00,785,143.25,2.86,13403,1.066
11,Parent Child - Parent,35,138,1997,1597.54,36,303.00,406.0,367.69,433.00,784,159.46,5.71,12869,1.024
12,Length Aware,28,522,2069,1955.71,130,407.00,427.5,448.79,455.50,808,117.77,0.00,12566,1.000
13,Fixed Character,31,799,2000,1961.10,235,414.00,429.0,452.23,454.00,785,102.17,0.00,14019,1.115
14,LLM Segment Then Chunk,37,20,2200,1659.19,8,250.00,434.0,379.73,470.00,862,188.03,10.81,14050,1.118
15,LLM Boundary Detection,29,952,2196,2076.48,291,434.00,452.0,476.76,485.00,856,108.19,0.00,13826,1.100
16,Paragraph Based,14,20,19809,3912.43,7,256.75,488.5,897.71,1070.00,4305,1086.33,14.29,12568,1.000
17,Dynamic Token Size,26,1136,2619,2106.73,357,485.50,493.0,483.42,497.75,500,30.85,0.00,12569,1.000
18,Overlapping Token,30,822,2722,2151.20,243,500.00,500.0,491.53,500.00,501,46.15,0.00,14746,1.173
19,Fixed Token,30,822,2722,2151.20,243,500.00,500.0,491.53,500.00,501,46.15,0.00,14746,1.173
20,Sliding Window Token,30,822,2722,2151.20,243,500.00,500.0,491.53,500.00,501,46.15,0.00,14746,1.173
21,Paragraph Group,7,1564,33410,13506.71,406,1550.50,2524.0,3113.71,4282.50,7200,2194.52,0.00,21796,1.734